# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import fauna_app.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0003_auto_20181207_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=fauna_app.options.tools.get_slider_image)),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=300)),
                ('btn_green', models.CharField(max_length=50)),
                ('btn_gray', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='globalmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
