# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0007_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
