# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import fauna_app.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0008_auto_20181210_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=fauna_app.options.tools.get_testimony_image),
        ),
    ]
