# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-25 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0011_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron poçt'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ad, Soyad'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Əlavə Mesajınız'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon'),
        ),
    ]
