# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-25 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0012_auto_20181225_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet_category',
            field=models.CharField(blank=True, choices=[('category1', 'Category1'), ('category2', 'Category2'), ('category3', 'Category3'), ('category4', 'Category4'), ('category5', 'Category5')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('a', 'A'), ('b', 'B')], max_length=150, null=True),
        ),
    ]
