# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0019_auto_20181229_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.BooleanField(choices=[(False, 'Female'), (True, 'Male')], default=False),
        ),
    ]
