# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0022_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
