# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0024_appointment_pet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fauna_app.Category'),
        ),
    ]
