# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0026_auto_20190106_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.BooleanField(choices=[(False, 'Female'), (True, 'Male')], default=False),
        ),
    ]
