# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0028_auto_20190109_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fauna_app.Product'),
        ),
    ]
