# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-13 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0032_auto_20190114_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',), 'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
