# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0036_auto_20190120_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('open', 'currently active'), ('submitted', 'has been ordered at the checkout'), ('merged', 'superceded by another basket'), ('frozen', 'the basket cannot be modified'), ('saved', 'for items to be purchased later')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancelled'), ('pending', 'Pending'), ('processed', 'Being processed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='test', max_length=40),
        ),
    ]
