# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-20 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0037_auto_20190120_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('submitted', 'has been ordered at the checkout'), ('merged', 'superceded by another basket'), ('open', 'currently active'), ('saved', 'for items to be purchased later'), ('frozen', 'the basket cannot be modified')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Being processed'), ('cancel', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.BooleanField(choices=[(False, 'Female'), (True, 'Male')], default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.BooleanField(choices=[(False, 'Female'), (True, 'Male')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
