# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0038_auto_20190120_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('submitted', 'has been ordered at the checkout'), ('frozen', 'the basket cannot be modified'), ('open', 'currently active'), ('saved', 'for items to be purchased later'), ('merged', 'superceded by another basket')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancelled'), ('pending', 'Pending'), ('processed', 'Being processed')], default='pending', max_length=10),
        ),
    ]
