# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-21 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fauna_app', '0040_auto_20190122_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('frozen', 'the basket cannot be modified'), ('open', 'currently active'), ('merged', 'superceded by another basket'), ('submitted', 'has been ordered at the checkout'), ('saved', 'for items to be purchased later')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancelled'), ('processed', 'Being processed'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
